name: Run Snoonaut Bot

on:
  schedule:
    - cron: '0 */12 * * *'  # setiap 12 jam
  workflow_dispatch:        # bisa dijalankan manual

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run snoonaut bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          COOKIE_1: ${{ secrets.COOKIE_1 }}
          COOKIE_2: ${{ secrets.COOKIE_2 }}
          COOKIE_3: ${{ secrets.COOKIE_3 }}
        run: node lim.js
