name: Run Snoonaut Bot

on:
  schedule:
    - cron: '0 */12 * * *' # Setiap 12 jam
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate package.json manually
        run: |
          echo '{
            "name": "snoonaut-bot",
            "version": "1.0.0",
            "main": "lim.js",
            "dependencies": {
              "axios": "^1.6.7",
              "dotenv": "^16.3.1",
              "https-proxy-agent": "^7.0.2"
            }
          }' > package.json

      - name: Install dependencies
        run: npm install

      - name: Run Snoonaut bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          COOKIE_1: ${{ secrets.COOKIE_1 }}
          COOKIE_2: ${{ secrets.COOKIE_2 }}
        run: node snoonaut.js
         
